### ISSUE TITLE
Use of IDE with a practical example

### ISSUE THREAD

**Issue by redskate** [culturegraph/metafacture-ide#40]
Hi Christoph

I use eclipse for my Java programming, downloaded the IDE and ... how can I see all the editors in action? I suppose I should create a Java program on something (metafacture-core I guess) but it seems not a quick way to see and evaluate.

Do you have an example of a Java Metafacture Project which I can open in eclipse to see all this magnificence?

Thank you in advance
Regards
Fabio

**Comment by fsteeg** [comment]
Hi Fabio! Did you see the [User Guide](https://github.com/culturegraph/metafacture-ide/wiki/User-Guide) for getting started with the IDE? Cheers, Fabian

**Comment by redskate** [comment]
Sure.

But I am too dumb to figure out what to do :) after having installed
your IDEplugin.

Cheers
Fabio


Am 19.6.15 um 19:53 schrieb Fabian Steeg:

**Comment by fsteeg** [comment]
There are quite detailed steps starting at: 
https://github.com/culturegraph/metafacture-ide/wiki/User-Guide#sample-usage
