### ISSUE TITLE
Installer fails: dependency "maven-dependency-plugin" no longer exists

### ISSUE THREAD

**Issue by thoffma** [culturegraph/metafacture-ide#50]
I've tried to set up the metafacture IDE but it fails because http://coderplus.com/m2e-update-sites/maven-dependency-plugin doesn't exist anymore.

Fetching content.xml from http://coderplus.com/m2e-update-sites/maven-dependency-plugin/
ERROR: org.eclipse.equinox.p2.metadata.repository code=1002 Unable to read repository at file:/C:/Users/name/.p2/org.eclipse.equinox.p2.repository/cache/content2023688405.xml.
java.io.IOException: The reference to entity "display" must end with the ';' delimiter.

**Comment by fsteeg** [comment]
I'm afraid the projects under the culturegraph organization can no longer be expected to work. All active development is happening under the metafacture organization at https://github.com/metafacture/. For tool support, we have the new VS code/codium extensions at https://metafacture.org/ide-extensions/ and the Playground at https://metafacture.org/playground/ (both experimental).

**Comment by thoffma** [comment]
I thought so, but I tried it anyway ;)
So, I will use the VS code extension.

**Comment by acka47** [comment]
> I'm afraid the projects under the culturegraph organization can no longer be expected to work.

Shouldn't we clarify this in the README then and archive the repos?

**Comment by fsteeg** [comment]
> Shouldn't we clarify this in the README then and archive the repos?

I've updated the About and will archive the repo.
